In [54]:
import os
from os.path import join as oj
import pandas as pd
import numpy as np
from scipy.stats import sem
from collections import defaultdict

from utils.utils import cwd, set_up_plotting

### for synthetic

In [28]:
synthetic1D_results_dir = oj('results', 'synthetic_1D')
with cwd(synthetic1D_results_dir):
    IG_df = pd.read_csv('final_IG-synthetic_1D.csv')
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,2.970379,0.123751,0.181599,0.041662
1,rand,89.899975,12.115724,0.190592,0.134769
2,entropy,17.092026,11.145370,0.922181,0.652080
3,joint,100.880978,16.043754,0.224912,0.159036
4,greedy_1,101.789537,17.340216,0.240916,0.170354
5,greedy_2,101.886465,16.049116,0.222766,0.157520
6,greedy_3,101.400644,16.542935,0.230721,0.163144
7,greedy_4,102.006382,15.601619,0.216300,0.152947
8,greedysum,101.750836,15.760847,0.219057,0.154896
9,dynamic_beta,95.355560,9.899903,0.146825,0.103821

In [30]:
combined_df = IG_df

In [31]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines     Final IG mean   Final IG std
0           ind     2.970 (0.124)  0.182 (0.042)
1          rand   89.900 (12.116)  0.191 (0.135)
2       entropy   17.092 (11.145)  0.922 (0.652)
3         joint  100.881 (16.044)  0.225 (0.159)
4      greedy_1  101.790 (17.340)  0.241 (0.170)
5      greedy_2  101.886 (16.049)  0.223 (0.158)
6      greedy_3  101.401 (16.543)  0.231 (0.163)
7      greedy_4  102.006 (15.602)  0.216 (0.153)
8     greedysum  101.751 (15.761)  0.219 (0.155)
9  dynamic_beta    95.356 (9.900)  0.147 (0.104)

In [32]:
with cwd(synthetic1D_results_dir):
    str_combined_df.to_csv("combined.csv", index=False)
    str_combined_df.to_latex("combined.tex", index=False)

#### 2D identical

In [36]:
synthetic2D_results_dir = oj('results', 'synthetic_2D')
with cwd(synthetic2D_results_dir):
    IG_df = pd.read_csv('final_IG-identical.csv')
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,20.536677,4.777267,0.465242,0.232621
1,rand,68.963015,0.413104,0.008471,0.005990
2,entropy,32.535781,1.087643,0.047276,0.033429
3,joint,71.093067,0.621196,0.012357,0.008738
4,greedy_1,81.846605,3.171089,0.054793,0.038744
5,greedy_2,81.884246,3.035125,0.052419,0.037066
6,greedy_3,82.422640,1.371454,0.023532,0.016639
7,greedy_4,83.346129,0.401753,0.006817,0.004820
8,greedysum,82.848273,0.899475,0.015354,0.010857
9,dynamic_beta,81.875569,0.678622,0.011722,0.008288

In [37]:
combined_df = IG_df

data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines   Final IG mean   Final IG std
0           ind  20.537 (4.777)  0.465 (0.233)
1          rand  68.963 (0.413)  0.008 (0.006)
2       entropy  32.536 (1.088)  0.047 (0.033)
3         joint  71.093 (0.621)  0.012 (0.009)
4      greedy_1  81.847 (3.171)  0.055 (0.039)
5      greedy_2  81.884 (3.035)  0.052 (0.037)
6      greedy_3  82.423 (1.371)  0.024 (0.017)
7      greedy_4  83.346 (0.402)  0.007 (0.005)
8     greedysum  82.848 (0.899)  0.015 (0.011)
9  dynamic_beta  81.876 (0.679)  0.012 (0.008)

In [38]:
with cwd(synthetic2D_results_dir):
    str_combined_df.to_csv("identical-combined.csv", index=False)
    str_combined_df.to_latex("identical-combined.tex", index=False)

#### 2D mismatch

In [39]:
synthetic2D_results_dir = oj('results', 'synthetic_2D')
with cwd(synthetic2D_results_dir):
    IG_df = pd.read_csv('final_IG-mismatch.csv')
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,42.130028,3.638657,0.376466,0.086367
1,rand,123.407096,2.739440,0.031393,0.022198
2,entropy,99.575581,2.313544,0.032858,0.023234
3,joint,143.569730,3.352799,0.033026,0.023353
4,greedy_1,133.613161,6.105022,0.064618,0.045692
5,greedy_2,138.877285,1.799216,0.018322,0.012955
6,greedy_3,140.195888,2.312407,0.023326,0.016494
7,greedy_4,143.726360,4.201849,0.041345,0.029235
8,greedysum,144.517684,3.881250,0.037981,0.026857
9,dynamic_beta,139.623409,0.692566,0.007015,0.004960

In [40]:
combined_df = IG_df

data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines    Final IG mean   Final IG std
0           ind   42.130 (3.639)  0.376 (0.086)
1          rand  123.407 (2.739)  0.031 (0.022)
2       entropy   99.576 (2.314)  0.033 (0.023)
3         joint  143.570 (3.353)  0.033 (0.023)
4      greedy_1  133.613 (6.105)  0.065 (0.046)
5      greedy_2  138.877 (1.799)  0.018 (0.013)
6      greedy_3  140.196 (2.312)  0.023 (0.016)
7      greedy_4  143.726 (4.202)  0.041 (0.029)
8     greedysum  144.518 (3.881)  0.038 (0.027)
9  dynamic_beta  139.623 (0.693)  0.007 (0.005)

In [41]:
with cwd(synthetic2D_results_dir):
    str_combined_df.to_csv("mismatch-combined.csv", index=False)
    str_combined_df.to_latex("mismatch-combined.tex", index=False)

### for material

In [57]:
material_results_dir = oj('results', 'material')
with cwd(material_results_dir):
    
    IG_df = pd.read_csv('final_IG-material.csv')
    MSE_df = pd.read_csv('material_regression.csv')

In [58]:
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,51.708492,7.369180,0.533238,0.142514
1,rand,171.949098,7.276352,0.059845,0.042317
2,entropy,99.825127,2.176201,0.030830,0.021800
3,joint,182.094968,7.226744,0.056125,0.039687
4,greedy_1,215.673019,29.651224,0.194429,0.137482
5,greedy_2,220.072859,31.979642,0.205505,0.145314
6,greedy_3,221.807985,32.489885,0.207151,0.146478
7,greedy_4,223.262568,14.591136,0.092425,0.065354
8,greedysum,223.459827,15.109229,0.095622,0.067615
9,dynamic_beta,215.205720,1.041256,0.006843,0.004838

In [59]:
MSE_df = MSE_df.rename(columns = {"Stderr": "Avg MSE (sem)", "Stderr Std": "Std MSE (sem)"})

MSE_df

      Baselines   Avg MSE  Avg MSE (sem)   Std MSE  Std MSE (sem)
0      greedy_1  0.222323       0.021101  0.030723       0.004569
1      greedy_2  0.262299       0.021892  0.053762       0.008760
2      greedy_3  0.225551       0.026504  0.027000       0.006593
3      greedy_4  0.172505       0.023747  0.034815       0.011747
4     greedysum  0.219118       0.012654  0.038695       0.008453
5  dynamic_beta  0.254988       0.035777  0.045795       0.014497
6         joint  0.209274       0.025947  0.040436       0.004301
7          rand  0.201360       0.017956  0.043836       0.004232
8       entropy  0.212001       0.016309  0.028284       0.005745
9           ind  0.227731       0.000748  0.062736       0.000406

In [60]:
combined_df = IG_df.merge(MSE_df, on='Baselines')

In [61]:
combined_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem),Avg MSE,Avg MSE (sem),Std MSE,Std MSE (sem)
0,ind,51.708492,7.369180,0.533238,0.142514,0.227731,0.000748,0.062736,0.000406
1,rand,171.949098,7.276352,0.059845,0.042317,0.201360,0.017956,0.043836,0.004232
2,entropy,99.825127,2.176201,0.030830,0.021800,0.212001,0.016309,0.028284,0.005745
3,joint,182.094968,7.226744,0.056125,0.039687,0.209274,0.025947,0.040436,0.004301
4,greedy_1,215.673019,29.651224,0.194429,0.137482,0.222323,0.021101,0.030723,0.004569
5,greedy_2,220.072859,31.979642,0.205505,0.145314,0.262299,0.021892,0.053762,0.008760
6,greedy_3,221.807985,32.489885,0.207151,0.146478,0.225551,0.026504,0.027000,0.006593
7,greedy_4,223.262568,14.591136,0.092425,0.065354,0.172505,0.023747,0.034815,0.011747
8,greedysum,223.459827,15.109229,0.095622,0.067615,0.219118,0.012654,0.038695,0.008453
9,dynamic_beta,215.205720,1.041256,0.006843,0.004838,0.254988,0.035777,0.045795,0.014497

In [62]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)

In [63]:
with cwd(material_results_dir):
    str_combined_df.to_csv("combined.csv", index=False)
    str_combined_df.to_latex("combined.tex", index=False)

### for drug discovery

In [64]:
drug_results_dir = oj('results', 'drug')
with cwd(drug_results_dir):
    
    IG_df = pd.read_csv('final_IG-drug.csv')
    MSE_df = pd.read_csv('regression_results.csv')    
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,1.576756,0.067972,0.105595,0.043109
1,rand,21.430299,6.593841,0.435136,0.307688
2,entropy,0.237875,0.068431,0.406835,0.287676
3,joint,56.872313,17.507612,0.435352,0.307841
4,greedy_1,65.173504,21.092631,0.457693,0.323638
5,greedy_2,65.616803,20.583978,0.443639,0.313700
6,greedy_3,65.207096,20.559498,0.445895,0.315295
7,greedy_4,66.626127,22.223345,0.471715,0.333553
8,greedysum,66.195503,19.392622,0.414308,0.292960
9,dynamic_beta,54.261293,12.926623,0.336907,0.238229

In [65]:
MSE_df = MSE_df.rename(columns = {"Stderr": "Avg MSE (sem)", "Stderr Std": "Std MSE (sem)"})
MSE_df

      Baselines   Avg MSE  Avg MSE (sem)   Std MSE  Std MSE (sem)
0      greedy_1  0.032886       0.006426  0.028504   6.959138e-03
1      greedy_2  0.022254       0.004153  0.021767   6.075434e-03
2      greedy_3  0.023507       0.003798  0.018160   3.507140e-03
3      greedy_4  0.021586       0.001697  0.017383   4.305229e-03
4     greedysum  0.031188       0.006728  0.027467   6.862513e-03
5  dynamic_beta  0.034357       0.005907  0.028413   6.610324e-03
6         joint  0.026464       0.003874  0.020138   3.877969e-03
7          rand  0.037305       0.005307  0.031519   6.825030e-03
8       entropy  0.056812       0.000000  0.054561   3.469447e-18
9           ind  0.042456       0.000000  0.036964   0.000000e+00

In [66]:
combined_df = IG_df.merge(MSE_df, on='Baselines')
combined_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem),Avg MSE,Avg MSE (sem),Std MSE,Std MSE (sem)
0,ind,1.576756,0.067972,0.105595,0.043109,0.042456,0.000000,0.036964,0.000000e+00
1,rand,21.430299,6.593841,0.435136,0.307688,0.037305,0.005307,0.031519,6.825030e-03
2,entropy,0.237875,0.068431,0.406835,0.287676,0.056812,0.000000,0.054561,3.469447e-18
3,joint,56.872313,17.507612,0.435352,0.307841,0.026464,0.003874,0.020138,3.877969e-03
4,greedy_1,65.173504,21.092631,0.457693,0.323638,0.032886,0.006426,0.028504,6.959138e-03
5,greedy_2,65.616803,20.583978,0.443639,0.313700,0.022254,0.004153,0.021767,6.075434e-03
6,greedy_3,65.207096,20.559498,0.445895,0.315295,0.023507,0.003798,0.018160,3.507140e-03
7,greedy_4,66.626127,22.223345,0.471715,0.333553,0.021586,0.001697,0.017383,4.305229e-03
8,greedysum,66.195503,19.392622,0.414308,0.292960,0.031188,0.006728,0.027467,6.862513e-03
9,dynamic_beta,54.261293,12.926623,0.336907,0.238229,0.034357,0.005907,0.028413,6.610324e-03

In [67]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines    Final IG mean   Final IG std        Avg MSE        Std MSE
0           ind    1.577 (0.068)  0.106 (0.043)  0.042 (0.000)  0.037 (0.000)
1          rand   21.430 (6.594)  0.435 (0.308)  0.037 (0.005)  0.032 (0.007)
2       entropy    0.238 (0.068)  0.407 (0.288)  0.057 (0.000)  0.055 (0.000)
3         joint  56.872 (17.508)  0.435 (0.308)  0.026 (0.004)  0.020 (0.004)
4      greedy_1  65.174 (21.093)  0.458 (0.324)  0.033 (0.006)  0.029 (0.007)
5      greedy_2  65.617 (20.584)  0.444 (0.314)  0.022 (0.004)  0.022 (0.006)
6      greedy_3  65.207 (20.559)  0.446 (0.315)  0.024 (0.004)  0.018 (0.004)
7      greedy_4  66.626 (22.223)  0.472 (0.334)  0.022 (0.002)  0.017 (0.004)
8     greedysum  66.196 (19.393)  0.414 (0.293)  0.031 (0.007)  0.027 (0.007)
9  dynamic_beta  54.261 (12.927)  0.337 (0.238)  0.034 (0.006)  0.028 (0.007)

In [68]:
with cwd(drug_results_dir):
    str_combined_df.to_csv("combined.csv", index=False)
    str_combined_df.to_latex("combined.tex", index=False)

### for DE-ODE

In [94]:
ODE_results_dir = oj('results', 'DE')
with cwd(ODE_results_dir):
    IG_df = pd.read_csv('final_IG-ODE.csv')
    MSE_df = pd.read_csv(oj('regression_results', 'ODE-regression-10-04-20:09:35.csv'))    
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,-6.617467,0.393083,0.178203,0.059401
1,rand,2.011054,1.266618,0.890711,0.629828
2,entropy,0.831535,0.382657,0.650795,0.460182
3,joint,2.888466,1.056713,0.517374,0.365839
4,greedy_1,3.348988,0.483843,0.204318,0.144475
5,greedy_2,3.486534,0.480130,0.194751,0.137710
6,greedy_3,3.175127,0.374131,0.166639,0.117832
7,greedy_4,3.705537,0.876857,0.334651,0.236634
8,greedysum,3.314806,0.746786,0.318605,0.225288
9,dynamic_beta,3.107244,0.550542,0.250571,0.177180

In [95]:
MSE_df = MSE_df.rename(columns = {"Stderr": "Avg MSE (sem)", "Stderr Std": "Std MSE (sem)"})
MSE_df

      Baselines   Avg MSE  Avg MSE (sem)   Std MSE  Std MSE (sem)
0      greedy_1  4.414846       0.069708  2.229695       0.238472
1      greedy_2  4.348969       0.237956  2.135969       0.171501
2      greedy_3  4.509461       0.188901  2.263646       0.224049
3      greedy_4  4.233805       0.031952  2.629065       0.052796
4     greedysum  4.431698       0.135749  2.343290       0.167145
5  dynamic_beta  4.320758       0.102841  2.438183       0.130126
6         joint  5.551462       0.802555  2.189718       0.465019
7          rand  4.505785       0.162808  2.342392       0.206684
8       entropy  4.116039       0.131804  2.524049       0.091083
9           ind  7.270185       0.198330  2.868899       0.080243

In [96]:
combined_df = IG_df.merge(MSE_df, on='Baselines')
combined_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem),Avg MSE,Avg MSE (sem),Std MSE,Std MSE (sem)
0,ind,-6.617467,0.393083,0.178203,0.059401,7.270185,0.198330,2.868899,0.080243
1,rand,2.011054,1.266618,0.890711,0.629828,4.505785,0.162808,2.342392,0.206684
2,entropy,0.831535,0.382657,0.650795,0.460182,4.116039,0.131804,2.524049,0.091083
3,joint,2.888466,1.056713,0.517374,0.365839,5.551462,0.802555,2.189718,0.465019
4,greedy_1,3.348988,0.483843,0.204318,0.144475,4.414846,0.069708,2.229695,0.238472
5,greedy_2,3.486534,0.480130,0.194751,0.137710,4.348969,0.237956,2.135969,0.171501
6,greedy_3,3.175127,0.374131,0.166639,0.117832,4.509461,0.188901,2.263646,0.224049
7,greedy_4,3.705537,0.876857,0.334651,0.236634,4.233805,0.031952,2.629065,0.052796
8,greedysum,3.314806,0.746786,0.318605,0.225288,4.431698,0.135749,2.343290,0.167145
9,dynamic_beta,3.107244,0.550542,0.250571,0.177180,4.320758,0.102841,2.438183,0.130126

In [97]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines   Final IG mean   Final IG std        Avg MSE        Std MSE
0           ind  -6.617 (0.393)  0.178 (0.059)  7.270 (0.198)  2.869 (0.080)
1          rand   2.011 (1.267)  0.891 (0.630)  4.506 (0.163)  2.342 (0.207)
2       entropy   0.832 (0.383)  0.651 (0.460)  4.116 (0.132)  2.524 (0.091)
3         joint   2.888 (1.057)  0.517 (0.366)  5.551 (0.803)  2.190 (0.465)
4      greedy_1   3.349 (0.484)  0.204 (0.144)  4.415 (0.070)  2.230 (0.238)
5      greedy_2   3.487 (0.480)  0.195 (0.138)  4.349 (0.238)  2.136 (0.172)
6      greedy_3   3.175 (0.374)  0.167 (0.118)  4.509 (0.189)  2.264 (0.224)
7      greedy_4   3.706 (0.877)  0.335 (0.237)  4.234 (0.032)  2.629 (0.053)
8     greedysum   3.315 (0.747)  0.319 (0.225)  4.432 (0.136)  2.343 (0.167)
9  dynamic_beta   3.107 (0.551)  0.251 (0.177)  4.321 (0.103)  2.438 (0.130)

In [98]:
with cwd(ODE_results_dir):
    str_combined_df.to_csv("ODE-combined.csv", index=False)
    str_combined_df.to_latex("ODE-combined.tex", index=False)

### for DE-VDP

In [69]:
VDP_results_dir = oj('results', 'DE')
with cwd(VDP_results_dir):
    
    IG_df = pd.read_csv('final_IG-VDP.csv')
    MSE_df = pd.read_csv('VDP-regression.csv')    
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,-8.843408,0.049899,0.016928,0.005643
1,rand,2.855470,0.851384,0.421660,0.298159
2,entropy,2.774742,0.839387,0.427814,0.302510
3,joint,2.786211,0.871947,0.442579,0.312951
4,greedy_1,2.723027,0.845098,0.438905,0.310352
5,greedy_2,2.750149,0.822212,0.422807,0.298970
6,greedy_3,2.822842,0.877391,0.439563,0.310818
7,greedy_4,2.898912,0.870699,0.424765,0.300354
8,greedysum,2.849837,0.846205,0.419924,0.296931
9,dynamic_beta,2.832807,0.854605,0.426642,0.301681

In [70]:
MSE_df = MSE_df.rename(columns = {"Stderr": "Avg MSE (sem)", "Stderr Std": "Std MSE (sem)"})
MSE_df

      Baselines   Avg MSE  Avg MSE (sem)   Std MSE  Std MSE (sem)
0      greedy_1  4.070467       0.368813  2.004384       0.511364
1      greedy_2  4.284268       0.140030  1.470074       0.448108
2      greedy_3  3.960905       0.366898  1.780499       0.356902
3      greedy_4  4.197850       0.319555  1.841132       0.355196
4     greedysum  3.959946       0.373225  1.221677       0.375216
5  dynamic_beta  3.831315       0.246508  1.335085       0.487051
6         joint  3.889320       0.298964  1.485932       0.345365
7          rand  4.973591       1.254244  2.457056       0.895329
8       entropy  4.472717       0.499482  1.860062       0.429533
9           ind  6.796462       0.554705  3.652913       0.390129

In [71]:
combined_df = IG_df.merge(MSE_df, on='Baselines')
combined_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem),Avg MSE,Avg MSE (sem),Std MSE,Std MSE (sem)
0,ind,-8.843408,0.049899,0.016928,0.005643,6.796462,0.554705,3.652913,0.390129
1,rand,2.855470,0.851384,0.421660,0.298159,4.973591,1.254244,2.457056,0.895329
2,entropy,2.774742,0.839387,0.427814,0.302510,4.472717,0.499482,1.860062,0.429533
3,joint,2.786211,0.871947,0.442579,0.312951,3.889320,0.298964,1.485932,0.345365
4,greedy_1,2.723027,0.845098,0.438905,0.310352,4.070467,0.368813,2.004384,0.511364
5,greedy_2,2.750149,0.822212,0.422807,0.298970,4.284268,0.140030,1.470074,0.448108
6,greedy_3,2.822842,0.877391,0.439563,0.310818,3.960905,0.366898,1.780499,0.356902
7,greedy_4,2.898912,0.870699,0.424765,0.300354,4.197850,0.319555,1.841132,0.355196
8,greedysum,2.849837,0.846205,0.419924,0.296931,3.959946,0.373225,1.221677,0.375216
9,dynamic_beta,2.832807,0.854605,0.426642,0.301681,3.831315,0.246508,1.335085,0.487051

In [72]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines   Final IG mean   Final IG std        Avg MSE        Std MSE
0           ind  -8.843 (0.050)  0.017 (0.006)  6.796 (0.555)  3.653 (0.390)
1          rand   2.855 (0.851)  0.422 (0.298)  4.974 (1.254)  2.457 (0.895)
2       entropy   2.775 (0.839)  0.428 (0.303)  4.473 (0.499)  1.860 (0.430)
3         joint   2.786 (0.872)  0.443 (0.313)  3.889 (0.299)  1.486 (0.345)
4      greedy_1   2.723 (0.845)  0.439 (0.310)  4.070 (0.369)  2.004 (0.511)
5      greedy_2   2.750 (0.822)  0.423 (0.299)  4.284 (0.140)  1.470 (0.448)
6      greedy_3   2.823 (0.877)  0.440 (0.311)  3.961 (0.367)  1.780 (0.357)
7      greedy_4   2.899 (0.871)  0.425 (0.300)  4.198 (0.320)  1.841 (0.355)
8     greedysum   2.850 (0.846)  0.420 (0.297)  3.960 (0.373)  1.222 (0.375)
9  dynamic_beta   2.833 (0.855)  0.427 (0.302)  3.831 (0.247)  1.335 (0.487)

In [73]:
with cwd(VDP_results_dir):
    str_combined_df.to_csv("VDP-combined.csv", index=False)
    str_combined_df.to_latex("VDP-combined.tex", index=False)

### SDE

In [89]:
SDE_results_dir = oj('results', 'DE')
with cwd(SDE_results_dir):
    IG_df = pd.read_csv('final_IG-SDE.csv')
    MSE_df = pd.read_csv(oj( 'regression_results', 'SDE-regression-10-04-21:03:36.csv'))    
IG_df = IG_df.rename(columns={'Methods': 'Baselines'})
IG_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem)
0,ind,-6.702847,0.092443,0.041375,0.013792
1,rand,5.303117,0.236624,0.063102,0.044620
2,entropy,4.432545,0.358905,0.114509,0.080970
3,joint,6.350725,0.680776,0.151599,0.107197
4,greedy_1,6.372102,0.706145,0.156721,0.110818
5,greedy_2,6.372791,0.844746,0.187461,0.132555
6,greedy_3,6.320790,0.953280,0.213287,0.150817
7,greedy_4,6.445102,0.705630,0.154833,0.109483
8,greedysum,6.392944,0.825324,0.182574,0.129099
9,dynamic_beta,6.279168,0.491861,0.110779,0.078332

In [90]:
MSE_df = MSE_df.rename(columns = {"Stderr": "Avg MSE (sem)", "Stderr Std": "Std MSE (sem)"})
MSE_df

      Baselines   Avg MSE  Avg MSE (sem)   Std MSE  Std MSE (sem)
0      greedy_1  4.668269       0.369038  1.420699       0.203741
1      greedy_2  4.329659       0.459776  1.279718       0.240443
2      greedy_3  4.753034       0.253966  1.277844       0.209647
3      greedy_4  4.555580       0.417552  1.326688       0.295527
4     greedysum  4.130306       0.467666  1.376866       0.276256
5  dynamic_beta  4.654190       0.266496  1.081960       0.206970
6         joint  4.603693       0.282605  1.361210       0.299397
7          rand  4.166453       0.319342  1.433462       0.251753
8       entropy  2.771840       0.422740  1.053537       0.075600
9           ind  5.179316       0.802955  2.613171       0.137215

In [91]:
combined_df = IG_df.merge(MSE_df, on='Baselines')
combined_df

,Baselines,Final IG mean,Final IG mean (sem),Final IG std,Final IG std (sem),Avg MSE,Avg MSE (sem),Std MSE,Std MSE (sem)
0,ind,-6.702847,0.092443,0.041375,0.013792,5.179316,0.802955,2.613171,0.137215
1,rand,5.303117,0.236624,0.063102,0.044620,4.166453,0.319342,1.433462,0.251753
2,entropy,4.432545,0.358905,0.114509,0.080970,2.771840,0.422740,1.053537,0.075600
3,joint,6.350725,0.680776,0.151599,0.107197,4.603693,0.282605,1.361210,0.299397
4,greedy_1,6.372102,0.706145,0.156721,0.110818,4.668269,0.369038,1.420699,0.203741
5,greedy_2,6.372791,0.844746,0.187461,0.132555,4.329659,0.459776,1.279718,0.240443
6,greedy_3,6.320790,0.953280,0.213287,0.150817,4.753034,0.253966,1.277844,0.209647
7,greedy_4,6.445102,0.705630,0.154833,0.109483,4.555580,0.417552,1.326688,0.295527
8,greedysum,6.392944,0.825324,0.182574,0.129099,4.130306,0.467666,1.376866,0.276256
9,dynamic_beta,6.279168,0.491861,0.110779,0.078332,4.654190,0.266496,1.081960,0.206970

In [92]:
data_rows = {}

for column in combined_df:
    if column == 'Baselines':
        data_rows['Baselines'] = combined_df['Baselines']
    else:
        if '(sem)' in column:
            pass
        else:
            data_row_str = []
            
            for mean, se in zip(combined_df[column], combined_df[f"{column} (sem)"]):
                
                data_row_str.append( f"{mean:.3f} ({se:.3f})" )
            
            data_rows[column] = data_row_str

str_combined_df = pd.DataFrame(data_rows)
str_combined_df

      Baselines   Final IG mean   Final IG std        Avg MSE        Std MSE
0           ind  -6.703 (0.092)  0.041 (0.014)  5.179 (0.803)  2.613 (0.137)
1          rand   5.303 (0.237)  0.063 (0.045)  4.166 (0.319)  1.433 (0.252)
2       entropy   4.433 (0.359)  0.115 (0.081)  2.772 (0.423)  1.054 (0.076)
3         joint   6.351 (0.681)  0.152 (0.107)  4.604 (0.283)  1.361 (0.299)
4      greedy_1   6.372 (0.706)  0.157 (0.111)  4.668 (0.369)  1.421 (0.204)
5      greedy_2   6.373 (0.845)  0.187 (0.133)  4.330 (0.460)  1.280 (0.240)
6      greedy_3   6.321 (0.953)  0.213 (0.151)  4.753 (0.254)  1.278 (0.210)
7      greedy_4   6.445 (0.706)  0.155 (0.109)  4.556 (0.418)  1.327 (0.296)
8     greedysum   6.393 (0.825)  0.183 (0.129)  4.130 (0.468)  1.377 (0.276)
9  dynamic_beta   6.279 (0.492)  0.111 (0.078)  4.654 (0.266)  1.082 (0.207)

In [93]:
with cwd(SDE_results_dir):
    str_combined_df.to_csv("SDE-combined.csv", index=False)
    str_combined_df.to_latex("SDE-combined.tex", index=False)